name 'gehel-graphite'
version '1.0.0'

author 'Guillaume Lederrey'
license 'Apache2'
project_page ''
source 'https://github.com/gehel42/puppet-graphite'
summary 'Puppet module for graphite'
description 'This module installs and manages graphite. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
